language: node_js
node_js:
  - '6.9'
env: TOTEM_DASHBOARD_CONFIG=config.dev
before_install:
  - npm install -g gulp
  - npm install -g bower
install:
  - npm install
  - bower install
script:
  - gulp test
  # Currently running protractor on PhantomJS is too buggy
  # - gulp protractor:dist
