language: node_js
node_js:
  - '0.12'
  - '0.10'
  # node-sass doesn't currently support iojs v3 https://github.com/sass/node-sass/issues/1053
  - 'iojs-v2.5.0'
env: TOTEM_DASHBOARD_CONFIG=config.dev
before_install:
  - npm install -g gulp
  - npm install -g bower
install:
  - npm install
  - bower install
script:
  - gulp test
  # Currently running protractor on PhantomJS is too buggy
  # - gulp protractor:dist
